id = "test-style-2"
api = 1
settings_adapter = "document-v1"
documents = ["cl"]
supports_locales = ["en-ch", "en-us"]
pages = [2]
default_pages = 2
substyles = ["cards", "timeline"]
default_substyle = "cards"
defaults = "../../shared/test-style-2/defaults.toml"
